name: ML Workflow CI (Conda)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    env:
      MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/mlruns"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: "mental_health_env"
        environment-file: MLProject/conda.yaml
        auto-activate-base: false
        miniforge-variant: Miniforge3
        miniforge-version: latest
        use-mamba: true

    - name: Verify Environment
      run: |
        conda info
        conda list
        echo "Tracking URI: $MLFLOW_TRACKING_URI"

    - name: Run MLflow Project
      run: |
        # Script ini akan otomatis menggunakan Env Var MLFLOW_TRACKING_URI di atas
        mlflow run MLProject --env-manager=local --experiment-name "CI_Conda_Run"

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/output/model.joblib